#!/usr/bin/env python3
"""Sync localization strings with Crowdin and open a pull request.

CI entrypoint for both directions of the Crowdin <-> repo flow. Three modes,
each a separate Bitrise workflow/trigger since they have different purposes:

  (no flags)
      Pulls source strings: downloads a Crowdin bundle (env var
      `CROWDIN_BUNDLE_ID`, required -- see NOTE below) and copies its English
      `.po` files into `strings/en/` (this also self-heals any file from a
      Crowdin-UI-side edit or deletion, since it overwrites with Crowdin's
      current state). If that changed any committed file, commits the result
      to a rolling branch and opens (or updates) a GitHub pull request.
      Requires `GH_TOKEN`.

  --push
      Pushes any new source strings added locally (a contributor hand-edits
      the target `.po` file directly, no script needed) to Crowdin, via an
      unconditional `crowdin upload sources`, then exits -- no pull, no
      commit, no PR. Crowdin matches by identifier, so this is a no-op for
      anything unchanged -- no local diffing needed. Does not require
      `GH_TOKEN`.

  --dry-run
      Preview the pull without switching branches, committing, pushing, or
      opening a PR. Combine with `--push` to preview just the push instead
      (`crowdin upload sources --dryrun`). Does not require `GH_TOKEN`.

Crowdin is the single source of truth for existing strings; they're never
hand-edited here. New strings are added by hand-editing the target `.po`
file directly and are gated on PRs by `scripts/crowdin_validator.py`, but
only this script ever writes to Crowdin.

NOTE (unresolved as of writing): unlike `crowdin upload`/`download`, which
only transfer *translations*, `crowdin download` has no source-only mode --
the CLI 4.12.0 has no `download sources` subcommand. loop-ios and
youversion-flutter-loop both work around this by downloading a *bundle*
(bundle 26, bundle 13) whose export includes the English/source locale.
There is not yet a Crowdin bundle scoped to this repo's `strings/en/*.po`
files -- one needs to be created in the Crowdin UI for project 257 (or an
existing bundle reused, if one already covers these exact files) before this
script's default mode can run for real. Until `CROWDIN_BUNDLE_ID` is set to a
valid bundle, this mode will fail loudly rather than silently do nothing.

Separately, this repo's `crowdin/crowdin.yml` uploads under the Crowdin path
implied by `strings/en/*.po` (relative to `base_path`). This is a *different*
Crowdin-side path than youversion-flutter-loop's existing
`assets/strings/en/*.po` upload -- pushing from here will very likely create
duplicate strings in project 257 rather than updating the same ones, unless
`crowdin/crowdin.yml` is given an explicit destination that matches Flutter's
existing Crowdin path. Confirm the intended Crowdin-side layout before
running `--push` for real.

Intended to run on Bitrise (scheduled/triggered). The runner must already
have:
  - `crowdin` CLI
  - `gh` CLI authenticated via `GH_TOKEN` (not required for `--push`/`--dry-run`)
  - env var `CROWDIN_API_TOKEN` (read by the crowdin CLI via crowdin/crowdin.yml)
  - env var `CROWDIN_BUNDLE_ID` (required for the default/pull mode; see NOTE)

Ported from youversion-flutter-loop/scripts/crowdin_sync.py, trimmed to just
the `.po` pull/push pipeline (no Dart/babel generation, since this repo is
platform-agnostic). The pull step itself lives in scripts/update_strings.py
(same split as loop-ios's update_strings.py / crowdin_sync.py) so it can be
run and tested standalone.
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path

CROWDIN_DIR = Path("crowdin")

# Rolling branch + PR settings (override via env in CI if needed).
BRANCH = os.environ.get("CROWDIN_SYNC_BRANCH", "chore/crowdin-sync")
BASE_BRANCH = os.environ.get("CROWDIN_SYNC_BASE", "main")
COMMIT_SUBJECT = "chore(l10n): sync strings from Crowdin"
COMMIT_MESSAGE = (
    f"{COMMIT_SUBJECT}\n\n"
    "Automated sync of source strings from Crowdin (project 257, "
    "strings/en/*.po)."
)
PR_BODY = (
    "Automated sync from Crowdin (project 257).\n\n"
    "Crowdin is the source of truth - do not hand-edit these files. "
    "Generated by `scripts/crowdin_sync.py`."
)

# Only the pulled source strings should land in the commit. The crowdin CLI's
# own scratch state is gitignored, but we scope `git add` explicitly to be safe.
OUTPUT_PATHS = [
    "strings/en",
]


def run(cmd, **kwargs):
    print("+", " ".join(cmd), flush=True)
    return subprocess.run(cmd, check=True, text=True, **kwargs)


def capture(cmd):
    result = subprocess.run(cmd, text=True, capture_output=True)
    if result.returncode != 0:
        # Surface stderr so failures (e.g. a gh auth/API error) show the real
        # message in the log instead of an opaque CalledProcessError.
        sys.stderr.write(result.stderr)
        raise subprocess.CalledProcessError(
            result.returncode, cmd, result.stdout, result.stderr
        )
    return result.stdout.strip()


def require_env(name):
    value = os.environ.get(name)
    if not value:
        sys.exit(f"ERROR: required environment variable {name} is unset or empty")
    return value


def has_staged_changes():
    # `git diff --cached --quiet` exits non-zero when something is staged.
    return subprocess.run(["git", "diff", "--cached", "--quiet"]).returncode != 0


def has_content_vs_base():
    # True if the sync branch's localization files differ from the base branch.
    return subprocess.run(
        ["git", "diff", "--quiet", f"origin/{BASE_BRANCH}", "HEAD", "--", *OUTPUT_PATHS]
    ).returncode != 0


def ensure_pr():
    # Open a PR for the sync branch, or report the one already open.
    try:
        open_pr = capture([
            "gh", "pr", "list", "--head", BRANCH, "--state", "open",
            "--json", "number", "--jq", ".[0].number // empty",
        ])
        if open_pr:
            print(f"Sync branch pushed; existing PR #{open_pr} is up to date.")
            return
        run([
            "gh", "pr", "create", "--base", BASE_BRANCH, "--head", BRANCH,
            "--title", COMMIT_SUBJECT, "--body", PR_BODY,
        ])
        print("Opened new Crowdin sync PR.")
    except subprocess.CalledProcessError:
        # The branch is already pushed; only the gh PR step failed (see the gh
        # error above -- usually GH_TOKEN missing Pull Requests scope or SSO
        # authorization). Exit with guidance instead of an opaque traceback.
        sys.exit(
            f"ERROR: pushed '{BRANCH}' but could not open/verify its PR via gh. "
            "Check GH_TOKEN has Pull Requests scope + SSO authorization, then re-run "
            f"-- or open a PR from '{BRANCH}' into '{BASE_BRANCH}' manually."
        )


def validate_sync_branch():
    # Guard against a misconfigured CROWDIN_SYNC_BRANCH (e.g. a typo like `main`
    # or a contributor branch) before any checkout or force push targets it.
    protected = {"main", "master", BASE_BRANCH}
    if BRANCH in protected:
        sys.exit(
            f"ERROR: refusing to run against protected branch {BRANCH!r}; "
            "CROWDIN_SYNC_BRANCH must be a dedicated sync branch"
        )
    if not BRANCH.startswith("chore/crowdin-"):
        sys.exit(
            f"ERROR: CROWDIN_SYNC_BRANCH {BRANCH!r} must start with 'chore/crowdin-'"
        )


def ensure_git_identity():
    existing = subprocess.run(["git", "config", "user.email"], capture_output=True, text=True)
    if existing.returncode != 0 or not existing.stdout.strip():
        run(["git", "config", "user.email",
             os.environ.get("CROWDIN_SYNC_GIT_EMAIL", "localization-bot@youversion.com")])
        run(["git", "config", "user.name",
             os.environ.get("CROWDIN_SYNC_GIT_NAME", "Crowdin Sync Bot")])


def parse_args():
    parser = argparse.ArgumentParser(
        description="Sync localization strings with Crowdin and open a pull request.",
    )
    parser.add_argument(
        "--push",
        action="store_true",
        help="push new local source strings to Crowdin, then exit (no pull, no PR)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help=(
            "preview without writing; on its own, previews the pull; combine "
            "with --push to preview just the push"
        ),
    )
    return parser.parse_args()


def push_new_strings(dry_run=False):
    # Push any locally-added source strings (hand-edited into the target
    # .po file directly; see scripts/crowdin_validator.py for the PR-time
    # gate) to Crowdin. Scoping to just strings/en/*.po is done via
    # crowdin/crowdin.yml's `files:` entry, not a CLI flag. This is
    # unconditional: Crowdin matches by identifier and no-ops anything
    # unchanged, so no local diffing is needed here. Never pass
    # --delete-obsolete; this must stay additive/update-only.
    cmd = ["crowdin", "upload", "sources"]
    if dry_run:
        cmd.append("--dryrun")
    run(cmd, cwd=str(CROWDIN_DIR))


def download_sources():
    # Re-download strings/en/*.po as currently stored on Crowdin -- self-heals
    # the repo after a Crowdin-UI-side edit or deletion. See
    # scripts/update_strings.py for why this needs a bundle (CROWDIN_BUNDLE_ID)
    # rather than a plain `crowdin download`.
    run([sys.executable, "scripts/update_strings.py"])


def preview_output_changes():
    status = capture(["git", "status", "--porcelain", "--", *OUTPUT_PATHS])
    if not status:
        return False

    print("\n--- Changes that would be committed ---")
    print(status)
    diff = subprocess.run(
        ["git", "diff", "--stat", "--", *OUTPUT_PATHS],
        capture_output=True,
        text=True,
    )
    if diff.stdout.strip():
        print(diff.stdout)
    return True


def push_command(dry_run=False):
    if dry_run:
        print("Dry run: previewing what would be pushed to Crowdin...")
    else:
        print("Pushing new local source strings to Crowdin...")
    push_new_strings(dry_run=dry_run)
    return 0


def dry_run():
    print("Dry run: downloading Crowdin strings and previewing changes...")
    download_sources()

    if not preview_output_changes():
        print("No localization changes from Crowdin; nothing to sync.")
    return 0


def main():
    args = parse_args()

    require_env("CROWDIN_API_TOKEN")

    root = capture(["git", "rev-parse", "--show-toplevel"])
    os.chdir(root)

    if args.push:
        return push_command(dry_run=args.dry_run)

    if args.dry_run:
        return dry_run()

    require_env("GH_TOKEN")

    validate_sync_branch()
    ensure_git_identity()

    # Start the sync branch fresh from the latest base branch. Also fetch the
    # rolling branch (if it exists) so --force-with-lease has a remote-tracking
    # ref to compare against before overwriting it.
    run(["git", "fetch", "origin", BASE_BRANCH])
    subprocess.run(["git", "fetch", "origin", BRANCH], text=True)
    run(["git", "switch", "-C", BRANCH, f"origin/{BASE_BRANCH}"])

    # 1. Pull from Crowdin and self-heal strings/en/.
    download_sources()

    # 2. Stage only the localization outputs.
    run(["git", "add", "--", *OUTPUT_PATHS])

    # 3. Commit any new changes.
    if has_staged_changes():
        run(["git", "commit", "-m", COMMIT_MESSAGE])

    # 4. Open (or update) the PR whenever the branch's localization content differs
    # from base -- even if THIS run committed nothing. This self-heals a prior run
    # that committed + pushed but failed before opening the PR (e.g. a transient gh
    # error): later runs find no new diff but still ensure the PR exists.
    if not has_content_vs_base():
        print("No localization changes from Crowdin; nothing to sync.")
        return 0

    run(["git", "push", "--force-with-lease", "origin", BRANCH])
    ensure_pr()
    return 0


if __name__ == "__main__":
    sys.exit(main())
